//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcFastFood.FastFoodSevice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceFastFood")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcFastFood.FastFoodSevice.Category CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> DisplayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcFastFood.FastFoodSevice.OrderDetail[] OrderDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> UnitPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VoteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcFastFood.FastFoodSevice.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((this.DiscountField.Equals(value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Display {
            get {
                return this.DisplayField;
            }
            set {
                if ((this.DisplayField.Equals(value) != true)) {
                    this.DisplayField = value;
                    this.RaisePropertyChanged("Display");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcFastFood.FastFoodSevice.OrderDetail[] OrderDetails {
            get {
                return this.OrderDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderDetailsField, value) != true)) {
                    this.OrderDetailsField = value;
                    this.RaisePropertyChanged("OrderDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIDField, value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Vote {
            get {
                return this.VoteField;
            }
            set {
                if ((this.VoteField.Equals(value) != true)) {
                    this.VoteField = value;
                    this.RaisePropertyChanged("Vote");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceFastFood")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcFastFood.FastFoodSevice.Product[] ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcFastFood.FastFoodSevice.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDetail", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceFastFood")]
    [System.SerializableAttribute()]
    public partial class OrderDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcFastFood.FastFoodSevice.Order OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcFastFood.FastFoodSevice.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcFastFood.FastFoodSevice.Order Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIDField, value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcFastFood.FastFoodSevice.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIDField, value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitPriceField, value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceFastFood")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcFastFood.FastFoodSevice.Account AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateCreateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcFastFood.FastFoodSevice.OrderDetail[] OrderDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcFastFood.FastFoodSevice.Account Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCreate {
            get {
                return this.DateCreateField;
            }
            set {
                if ((this.DateCreateField.Equals(value) != true)) {
                    this.DateCreateField = value;
                    this.RaisePropertyChanged("DateCreate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcFastFood.FastFoodSevice.OrderDetail[] OrderDetails {
            get {
                return this.OrderDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderDetailsField, value) != true)) {
                    this.OrderDetailsField = value;
                    this.RaisePropertyChanged("OrderDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIDField, value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Payment {
            get {
                return this.PaymentField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentField, value) != true)) {
                    this.PaymentField = value;
                    this.RaisePropertyChanged("Payment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientAddress {
            get {
                return this.RecipientAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientAddressField, value) != true)) {
                    this.RecipientAddressField = value;
                    this.RaisePropertyChanged("RecipientAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalPrice {
            get {
                return this.TotalPriceField;
            }
            set {
                if ((this.TotalPriceField.Equals(value) != true)) {
                    this.TotalPriceField = value;
                    this.RaisePropertyChanged("TotalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceFastFood")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcFastFood.FastFoodSevice.Order[] OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcFastFood.FastFoodSevice.UserType UserTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserTypeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcFastFood.FastFoodSevice.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcFastFood.FastFoodSevice.UserType UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserTypeID {
            get {
                return this.UserTypeIDField;
            }
            set {
                if ((this.UserTypeIDField.Equals(value) != true)) {
                    this.UserTypeIDField = value;
                    this.RaisePropertyChanged("UserTypeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserType", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceFastFood")]
    [System.SerializableAttribute()]
    public partial class UserType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcFastFood.FastFoodSevice.Account[] AccountsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserType1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcFastFood.FastFoodSevice.Account[] Accounts {
            get {
                return this.AccountsField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountsField, value) != true)) {
                    this.AccountsField = value;
                    this.RaisePropertyChanged("Accounts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType1 {
            get {
                return this.UserType1Field;
            }
            set {
                if ((object.ReferenceEquals(this.UserType1Field, value) != true)) {
                    this.UserType1Field = value;
                    this.RaisePropertyChanged("UserType1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FastFoodSevice.IFastFoodService")]
    public interface IFastFoodService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/tong", ReplyAction="http://tempuri.org/IFastFoodService/tongResponse")]
        int tong(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/getAllProduct", ReplyAction="http://tempuri.org/IFastFoodService/getAllProductResponse")]
        MvcFastFood.FastFoodSevice.Product[] getAllProduct();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/getProductByID", ReplyAction="http://tempuri.org/IFastFoodService/getProductByIDResponse")]
        MvcFastFood.FastFoodSevice.Product getProductByID(string productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/insertProduct", ReplyAction="http://tempuri.org/IFastFoodService/insertProductResponse")]
        bool insertProduct(MvcFastFood.FastFoodSevice.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/deleteProduct", ReplyAction="http://tempuri.org/IFastFoodService/deleteProductResponse")]
        bool deleteProduct(string productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/updateProduct", ReplyAction="http://tempuri.org/IFastFoodService/updateProductResponse")]
        bool updateProduct(MvcFastFood.FastFoodSevice.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/search", ReplyAction="http://tempuri.org/IFastFoodService/searchResponse")]
        MvcFastFood.FastFoodSevice.Product[] search(string productName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/getProductByCategory", ReplyAction="http://tempuri.org/IFastFoodService/getProductByCategoryResponse")]
        MvcFastFood.FastFoodSevice.Product[] getProductByCategory(int categoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/getAllCategory", ReplyAction="http://tempuri.org/IFastFoodService/getAllCategoryResponse")]
        MvcFastFood.FastFoodSevice.Category[] getAllCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/getCategoryByID", ReplyAction="http://tempuri.org/IFastFoodService/getCategoryByIDResponse")]
        MvcFastFood.FastFoodSevice.Category getCategoryByID(int categoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/insertCategory", ReplyAction="http://tempuri.org/IFastFoodService/insertCategoryResponse")]
        bool insertCategory(MvcFastFood.FastFoodSevice.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/updateCategory", ReplyAction="http://tempuri.org/IFastFoodService/updateCategoryResponse")]
        bool updateCategory(MvcFastFood.FastFoodSevice.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/deteteCategory", ReplyAction="http://tempuri.org/IFastFoodService/deteteCategoryResponse")]
        bool deteteCategory(int categoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/getAllOrder", ReplyAction="http://tempuri.org/IFastFoodService/getAllOrderResponse")]
        MvcFastFood.FastFoodSevice.Order[] getAllOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/getOrderByID", ReplyAction="http://tempuri.org/IFastFoodService/getOrderByIDResponse")]
        MvcFastFood.FastFoodSevice.Order getOrderByID(string orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/insertOrder", ReplyAction="http://tempuri.org/IFastFoodService/insertOrderResponse")]
        bool insertOrder(MvcFastFood.FastFoodSevice.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/updateOrder", ReplyAction="http://tempuri.org/IFastFoodService/updateOrderResponse")]
        bool updateOrder(MvcFastFood.FastFoodSevice.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/deteteOrder", ReplyAction="http://tempuri.org/IFastFoodService/deteteOrderResponse")]
        bool deteteOrder(int orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/insertOrderDetail", ReplyAction="http://tempuri.org/IFastFoodService/insertOrderDetailResponse")]
        bool insertOrderDetail(MvcFastFood.FastFoodSevice.OrderDetail orderDetai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/getOrderDetailByID", ReplyAction="http://tempuri.org/IFastFoodService/getOrderDetailByIDResponse")]
        MvcFastFood.FastFoodSevice.OrderDetail getOrderDetailByID(string order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/getAllAccount", ReplyAction="http://tempuri.org/IFastFoodService/getAllAccountResponse")]
        MvcFastFood.FastFoodSevice.Account[] getAllAccount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/getAccountByID", ReplyAction="http://tempuri.org/IFastFoodService/getAccountByIDResponse")]
        MvcFastFood.FastFoodSevice.Account getAccountByID(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/insertAccount", ReplyAction="http://tempuri.org/IFastFoodService/insertAccountResponse")]
        bool insertAccount(MvcFastFood.FastFoodSevice.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/updateAccount", ReplyAction="http://tempuri.org/IFastFoodService/updateAccountResponse")]
        bool updateAccount(MvcFastFood.FastFoodSevice.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/deteteAccount", ReplyAction="http://tempuri.org/IFastFoodService/deteteAccountResponse")]
        bool deteteAccount(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/login", ReplyAction="http://tempuri.org/IFastFoodService/loginResponse")]
        MvcFastFood.FastFoodSevice.Account[] login(string userName, string passWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodService/getAllUserType", ReplyAction="http://tempuri.org/IFastFoodService/getAllUserTypeResponse")]
        MvcFastFood.FastFoodSevice.UserType[] getAllUserType();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFastFoodServiceChannel : MvcFastFood.FastFoodSevice.IFastFoodService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FastFoodServiceClient : System.ServiceModel.ClientBase<MvcFastFood.FastFoodSevice.IFastFoodService>, MvcFastFood.FastFoodSevice.IFastFoodService {
        
        public FastFoodServiceClient() {
        }
        
        public FastFoodServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FastFoodServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FastFoodServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FastFoodServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int tong(int a, int b) {
            return base.Channel.tong(a, b);
        }
        
        public MvcFastFood.FastFoodSevice.Product[] getAllProduct() {
            return base.Channel.getAllProduct();
        }
        
        public MvcFastFood.FastFoodSevice.Product getProductByID(string productID) {
            return base.Channel.getProductByID(productID);
        }
        
        public bool insertProduct(MvcFastFood.FastFoodSevice.Product product) {
            return base.Channel.insertProduct(product);
        }
        
        public bool deleteProduct(string productID) {
            return base.Channel.deleteProduct(productID);
        }
        
        public bool updateProduct(MvcFastFood.FastFoodSevice.Product product) {
            return base.Channel.updateProduct(product);
        }
        
        public MvcFastFood.FastFoodSevice.Product[] search(string productName) {
            return base.Channel.search(productName);
        }
        
        public MvcFastFood.FastFoodSevice.Product[] getProductByCategory(int categoryID) {
            return base.Channel.getProductByCategory(categoryID);
        }
        
        public MvcFastFood.FastFoodSevice.Category[] getAllCategory() {
            return base.Channel.getAllCategory();
        }
        
        public MvcFastFood.FastFoodSevice.Category getCategoryByID(int categoryID) {
            return base.Channel.getCategoryByID(categoryID);
        }
        
        public bool insertCategory(MvcFastFood.FastFoodSevice.Category category) {
            return base.Channel.insertCategory(category);
        }
        
        public bool updateCategory(MvcFastFood.FastFoodSevice.Category category) {
            return base.Channel.updateCategory(category);
        }
        
        public bool deteteCategory(int categoryID) {
            return base.Channel.deteteCategory(categoryID);
        }
        
        public MvcFastFood.FastFoodSevice.Order[] getAllOrder() {
            return base.Channel.getAllOrder();
        }
        
        public MvcFastFood.FastFoodSevice.Order getOrderByID(string orderID) {
            return base.Channel.getOrderByID(orderID);
        }
        
        public bool insertOrder(MvcFastFood.FastFoodSevice.Order order) {
            return base.Channel.insertOrder(order);
        }
        
        public bool updateOrder(MvcFastFood.FastFoodSevice.Order order) {
            return base.Channel.updateOrder(order);
        }
        
        public bool deteteOrder(int orderID) {
            return base.Channel.deteteOrder(orderID);
        }
        
        public bool insertOrderDetail(MvcFastFood.FastFoodSevice.OrderDetail orderDetai) {
            return base.Channel.insertOrderDetail(orderDetai);
        }
        
        public MvcFastFood.FastFoodSevice.OrderDetail getOrderDetailByID(string order) {
            return base.Channel.getOrderDetailByID(order);
        }
        
        public MvcFastFood.FastFoodSevice.Account[] getAllAccount() {
            return base.Channel.getAllAccount();
        }
        
        public MvcFastFood.FastFoodSevice.Account getAccountByID(string userName) {
            return base.Channel.getAccountByID(userName);
        }
        
        public bool insertAccount(MvcFastFood.FastFoodSevice.Account account) {
            return base.Channel.insertAccount(account);
        }
        
        public bool updateAccount(MvcFastFood.FastFoodSevice.Account account) {
            return base.Channel.updateAccount(account);
        }
        
        public bool deteteAccount(string userName) {
            return base.Channel.deteteAccount(userName);
        }
        
        public MvcFastFood.FastFoodSevice.Account[] login(string userName, string passWord) {
            return base.Channel.login(userName, passWord);
        }
        
        public MvcFastFood.FastFoodSevice.UserType[] getAllUserType() {
            return base.Channel.getAllUserType();
        }
    }
}
