//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceFastFood
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderImport
    {
        public OrderImport()
        {
            this.OrderImportDetails = new HashSet<OrderImportDetail>();
        }
    
        public string OrderImportID { get; set; }
        public Nullable<System.DateTime> DateImport { get; set; }
        public Nullable<double> TotalPrice { get; set; }
    
        public virtual ICollection<OrderImportDetail> OrderImportDetails { get; set; }
    }
}
